### ISSUE TITLE
Question concernant getMinimum / getMaximum

### ISSUE THREAD

**Issue by Roffray** [jclaveau/php-logical-filter#48]
https://github.com/jclaveau/php-logical-filter/blob/751a0895af69b9df32657388ff31b9df0e9c44bb/src/Rule/AboveRule.php#L38

getMinimum ne devrait pas plutôt s'appeler getValue car cela retourne la valeur de la règle et non un minimum ?
Idem getMaximum pour BelowRule, BetweenRule, ...

Merci,
#TeamVuble

**Comment by jclaveau** [comment]
getMinimum retroune la "valeur minmum possible".
Ceci dit la question est posée de manière plus générale et j'ai implémenté la méthode getValues pour ça (car pour une règle comme BetweenRule, par exemple, il y a un maximum et un minimum).

Pour aller plus loin dans cette reflexion il faut avoir joué un peu plus avec les règles et les limites de l'héritage comme abstraction : Au cours du process de simplification par exemple, des OrRules deviennent des AndRules, Not(EqualRule) peut devenir OrRule(AboveRule, BelowRule).

On voit ici que l'arborescence avec héritage et trop rigide ici puisque un objet ne peut changer de classe. Il y a alors deux approches possibles à vue de nez :  
+ compotementale
+ ajouter un objet RuleNode qui définisse l'arbre

Pour des question de perf (mémoire principalement) et de lisibilité, je penche plutôt pour la première, mais ça nécessiterait une session de benchmarks d'abord (les behaviors nécessitant d'utiliser les méthodes magiques __get, __call, __set en PHP).

Ce genre de réflexions sont listées ici : https://github.com/jclaveau/php-logical-filter/milestone/3

**Comment by jclaveau** [comment]
Au final j'ai gardé getMinimum() et getMaximum() pour >= et <= et renommé en getLowerLimit() et getUpperLimit() pour les règles > et < pour lesquelles les "minimums et maximums" sont exclus
